import { CreateBucketCommand, HeadBucketCommand } from "@aws-sdk/client-s3";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { bucket, putObject, s3 } from "../services/storage";

export type DemoSeedObjectSpec = {
  spacesKey: string;
  originalName: string;
  caseNumber?: string | null;
  clientName?: string | null;
  routedCaseId?: string | null;
  status: string;
  hasOffer?: boolean;
};

async function ensureDemoSeedBucket(): Promise<void> {
  try {
    await s3.send(new HeadBucketCommand({ Bucket: bucket }));
    return;
  } catch (error) {
    const httpStatus = (error as { $metadata?: { httpStatusCode?: number } })?.$metadata?.httpStatusCode;
    const code = String((error as { name?: string; Code?: string; code?: string })?.Code ?? (error as { code?: string })?.code ?? (error as { name?: string })?.name ?? "");
    const isMissingBucket = httpStatus == 404 || code === "NotFound" || code === "NoSuchBucket" || code === "NoSuchBucketError";
    if (!isMissingBucket) throw error;
  }

  try {
    await s3.send(new CreateBucketCommand({ Bucket: bucket }));
  } catch (error) {
    const code = String((error as { name?: string; Code?: string; code?: string })?.Code ?? (error as { code?: string })?.code ?? (error as { name?: string })?.name ?? "");
    if (code !== "BucketAlreadyOwnedByYou" && code !== "BucketAlreadyExists") {
      throw error;
    }
  }
}

async function buildDemoPdfBuffer(spec: DemoSeedObjectSpec): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const left = 56;
  let y = 730;

  page.drawText("Onyx Intel Demo Seed Document", {
    x: left,
    y,
    size: 20,
    font: bold,
    color: rgb(0.14, 0.17, 0.23),
  });
  y -= 34;

  const rows = [
    ["File", spec.originalName],
    ["Storage key", spec.spacesKey],
    ["Case number", spec.caseNumber ?? "Unassigned"],
    ["Client", spec.clientName ?? "Unknown"],
    ["Routed case", spec.routedCaseId ?? "Not routed"],
    ["Status", spec.status],
    ["Settlement offer", spec.hasOffer ? "$50,000 recognized in demo seed" : "None"],
  ] as const;

  for (const [label, value] of rows) {
    page.drawText(`${label}:`, {
      x: left,
      y,
      size: 11,
      font: bold,
      color: rgb(0.16, 0.19, 0.24),
    });
    page.drawText(value, {
      x: left + 120,
      y,
      size: 11,
      font,
      color: rgb(0.2, 0.22, 0.28),
      maxWidth: 400,
      lineHeight: 14,
    });
    y -= 22;
  }

  y -= 10;
  const note = [
    "This PDF is generated by the local demo seed flow.",
    "It exists so case packet exports in local development include real document objects",
    "that match the seeded Document.spacesKey values.",
  ];
  for (const line of note) {
    page.drawText(line, {
      x: left,
      y,
      size: 11,
      font,
      color: rgb(0.28, 0.31, 0.37),
    });
    y -= 18;
  }

  page.drawRectangle({ x: left, y: 120, width: 500, height: 1, color: rgb(0.87, 0.89, 0.92) });
  page.drawText("Generated for demo packet export verification.", {
    x: left,
    y: 96,
    size: 10,
    font,
    color: rgb(0.45, 0.48, 0.53),
  });

  return Buffer.from(await pdf.save());
}

export async function ensureDemoSeedObjects(specs: DemoSeedObjectSpec[]): Promise<void> {
  await ensureDemoSeedBucket();
  for (const spec of specs) {
    const buffer = await buildDemoPdfBuffer(spec);
    await putObject(spec.spacesKey, buffer, "application/pdf");
  }
}
