/**
 * PM2 ecosystem config for doc-platform (API, worker, web).
 * Run from repo root: pm2 start ecosystem.config.cjs
 */
const path = require("path");

module.exports = {
  apps: [
    {
      name: "doc-platform-api",
      cwd: path.join(__dirname, "apps", "api"),
      script: "dist/http/server.js",
      interpreter: "node",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 10000,
      listen_timeout: 10000,
      max_memory_restart: "700M",
      merge_logs: true,
      time: true,
      out_file: path.join(__dirname, "logs", "pm2", "api-out.log"),
      error_file: path.join(__dirname, "logs", "pm2", "api-error.log"),
      env: { NODE_ENV: "production" },
    },
    {
      name: "doc-platform-worker",
      cwd: path.join(__dirname, "apps", "api"),
      script: "dist/workers/worker.js",
      interpreter: "node",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 10000,
      listen_timeout: 10000,
      max_memory_restart: "700M",
      merge_logs: true,
      time: true,
      out_file: path.join(__dirname, "logs", "pm2", "worker-out.log"),
      error_file: path.join(__dirname, "logs", "pm2", "worker-error.log"),
      env: { NODE_ENV: "production" },
    },
    {
      name: "doc-platform-web",
      cwd: path.join(__dirname, "apps", "web"),
      script: path.join(__dirname, "scripts", "start-service-with-build-info.mjs"),
      args: ["web", "node", "node_modules/next/dist/bin/next", "start"],
      interpreter: "node",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 10000,
      listen_timeout: 15000,
      max_memory_restart: "900M",
      merge_logs: true,
      time: true,
      out_file: path.join(__dirname, "logs", "pm2", "web-out.log"),
      error_file: path.join(__dirname, "logs", "pm2", "web-error.log"),
      env: { NODE_ENV: "production", PORT: "3000" },
    },
  ],
};
