import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NotificationsBell from "./dashboard/NotificationsBell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            borderBottom: "1px solid #e5e5e5",
            padding: "12px 24px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            background: "#fafafa",
          }}
        >
          <Link
            href="/dashboard"
            style={{
              fontSize: 16,
              fontWeight: 600,
              color: "#111",
              textDecoration: "none",
            }}
          >
            Doc Platform
          </Link>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <Link
              href="/search"
              style={{ fontSize: 14, color: "#111", textDecoration: "underline" }}
            >
              Search
            </Link>
            <Link
              href="/notifications"
              style={{ fontSize: 14, color: "#111", textDecoration: "underline" }}
            >
              Notifications
            </Link>
            <NotificationsBell />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
