export const projectSeeds = [
  {
    name: "doc-platform",
    slug: "doc-platform",
    description: "Healthcare document intake and case routing platform.",
    repoUrl: "https://github.com/oceanwonders42-crypto/doc-platform",
    repoName: "oceanwonders42-crypto/doc-platform",
    defaultBranch: "main",
    deployType: "droplet",
    deployTargetName: "ubuntu-s-1vcpu-512mb-10gb-nyc3-01",
    deployTargetIdOrHost: "167.172.233.17",
    environment: "prod",
    containerImage: null,
    containerRegistryUrl: null,
    publicUrl: "http://167.172.233.17",
    sshHost: "167.172.233.17",
    sshPort: 22,
    sshUser: "root",
    appPath: "/root/doc-platform",
    deployMode: "git_pnpm_pm2",
    processManager: "pm2",
    runtimeServices: "api (id 0), web (id 5)",
    apiServiceName: "api",
    apiServiceId: 0,
    webServiceName: "web",
    webServiceId: 5,
    deployCommand:
      "cd /root/doc-platform && git pull origin main && pnpm install --frozen-lockfile && pnpm run build && pm2 restart api --update-env && pm2 restart web --update-env && pm2 save",
    restartCommand: "pm2 restart api --update-env && pm2 restart web --update-env",
    logCommand: "pm2 logs api --lines 50 --nostream && pm2 logs web --lines 50 --nostream",
    healthCheckUrl: "http://127.0.0.1:4000/health",
    internalApiUrl: "http://127.0.0.1:4000",
    internalApiHealthUrl: "http://127.0.0.1:4000/health",
    internalApiHealthzUrl: "http://127.0.0.1:4000/healthz",
    dockerfileStatus: "unknown",
    composeUsage: "docker-compose.yml exists but is not used in the live deploy. No compose service name is currently used.",
    apiHealthy: true,
    webHealthy: false,
    publicHealthy: false,
    runtimeStatus: "degraded",
    lastRuntimeCheckAt: new Date("2026-03-19T20:15:00Z"),
    runtimeReason: "Public traffic is degraded because the web process is missing a Next production build in apps/web/.next.",
    runtimeDetails: {
      cause: "PM2 web logs show the Next production server cannot find the '.next' build output in apps/web/.next.",
      api: {
        label: "API health",
        url: "http://127.0.0.1:4000/health",
        status: "healthy",
        statusCode: 200,
        summary: "API /health returns 200 OK.",
      },
      healthz: {
        label: "API healthz",
        url: "http://127.0.0.1:4000/healthz",
        status: "healthy",
        statusCode: 200,
        summary: "API /healthz returns 200 OK.",
      },
      public: {
        label: "Public entrypoint",
        url: "http://167.172.233.17",
        status: "degraded",
        statusCode: 502,
        summary: "Public URL returns 502 Bad Gateway.",
      },
      web: {
        name: "web",
        id: 5,
        manager: "pm2",
        status: "unhealthy",
        summary: "PM2 web process is up but serving a broken production Next.js runtime.",
        logHint:
          "Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server.",
      },
      pm2Services: [
        {
          name: "api",
          id: 0,
          manager: "pm2",
          status: "healthy",
          summary: "API process is online and responding on the internal health endpoints.",
        },
        {
          name: "web",
          id: 5,
          manager: "pm2",
          status: "unhealthy",
          summary: "Web process is unhealthy because the production build output is missing.",
          logHint:
            "Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server.",
        },
      ],
      recommendedAction: "Run the web build on the server, then restart the PM2 web process and re-check the public URL.",
    },
    isActive: true,
  },
  {
    name: "marketing-site",
    slug: "marketing-site",
    description: "Main marketing website and conversion funnels.",
    repoUrl: "https://github.com/onyx-internal/marketing-site",
    repoName: "onyx-internal/marketing-site",
    defaultBranch: "main",
    deployType: "droplet",
    deployTargetName: "marketing-edge",
    deployTargetIdOrHost: "167.99.14.20",
    environment: "prod",
    containerImage: "registry.digitalocean.com/onyx/marketing-site:web",
    containerRegistryUrl: "registry.digitalocean.com/onyx/marketing-site",
    deployCommand: "ssh deploy@167.99.14.20 'docker compose up -d'",
    healthCheckUrl: "https://marketing.internal/healthz",
    isActive: true,
  },
  {
    name: "client-portal",
    slug: "client-portal",
    description: "Authenticated client operations portal.",
    repoUrl: "https://github.com/onyx-internal/client-portal",
    repoName: "onyx-internal/client-portal",
    defaultBranch: "main",
    deployType: "app_platform",
    deployTargetName: "client-portal-staging",
    deployTargetIdOrHost: "app-81df4-client-portal",
    environment: "staging",
    containerImage: "registry.digitalocean.com/onyx/client-portal:web",
    containerRegistryUrl: "registry.digitalocean.com/onyx/client-portal",
    deployCommand: "doctl apps create-deployment client-portal-staging",
    healthCheckUrl: "https://client-portal.staging.internal/healthz",
    isActive: true,
  },
  {
    name: "automations",
    slug: "automations",
    description: "Internal automation runners and workflow services.",
    repoUrl: "https://github.com/onyx-internal/automations",
    repoName: "onyx-internal/automations",
    defaultBranch: "main",
    deployType: "other",
    deployTargetName: "worker-lab",
    deployTargetIdOrHost: "runner-02.internal",
    environment: "dev",
    containerImage: "registry.digitalocean.com/onyx/automations:worker",
    containerRegistryUrl: "registry.digitalocean.com/onyx/automations",
    deployCommand: "docker compose up -d worker",
    healthCheckUrl: null,
    isActive: true,
  },
];

export const taskSeeds = [
  {
    projectSlug: "doc-platform",
    title: "Batch Clio handoff export",
    description: "Ship the nightly handoff export so support can stop manual CSV assembly.",
    status: "in_progress",
    executionMode: "github_pr",
    executionStatus: "in_progress",
    priority: "urgent",
    assignedAgent: "codex",
    linkedGithubRepo: "onyx-internal/doc-platform",
    githubIssueUrl: "https://github.com/onyx-internal/doc-platform/issues/182",
    githubPrUrl: "https://github.com/onyx-internal/doc-platform/pull/188",
    deployUrl: "https://cloud.digitalocean.com/apps/app-8cf81-doc-platform",
    branchName: "feature/clio-handoff-export",
    linkedGithubBranch: "feature/clio-handoff-export",
    linkedCommitSha: "1f3ac9de11be4402",
    blockedReason: null,
    needsDecision: false,
    nextStep: "Finalize export serializer and rerun packet QA.",
  },
  {
    projectSlug: "client-portal",
    title: "Fix login redirect",
    description: "Resolve the loop that hits staging users after password reset.",
    status: "review",
    executionMode: "github_pr",
    executionStatus: "review",
    priority: "high",
    assignedAgent: "cursor",
    linkedGithubRepo: "onyx-internal/client-portal",
    githubIssueUrl: "https://github.com/onyx-internal/client-portal/issues/54",
    githubPrUrl: "https://github.com/onyx-internal/client-portal/pull/61",
    deployUrl: null,
    branchName: "fix/reset-redirect-loop",
    linkedGithubBranch: "fix/reset-redirect-loop",
    linkedCommitSha: "74badd8ef2261f92",
    blockedReason: null,
    needsDecision: false,
    nextStep: "Regression-check invite flow in staging.",
  },
  {
    projectSlug: "automations",
    title: "Wire GitHub integration",
    description: "Create the first repo sync adapter for issues, PRs, and branch references.",
    status: "ready",
    executionMode: "agent_prompt",
    executionStatus: "queued",
    priority: "high",
    assignedAgent: "claude",
    linkedGithubRepo: "onyx-internal/automations",
    githubIssueUrl: null,
    githubPrUrl: null,
    deployUrl: null,
    branchName: "design/github-sync-adapter",
    blockedReason: null,
    needsDecision: true,
    nextStep: "Choose between webhook-first or polling-first MVP sync.",
  },
  {
    projectSlug: "marketing-site",
    title: "Review deploy health checks",
    description: "Normalize health endpoints before we add deployment monitoring.",
    status: "blocked",
    executionMode: "runtime_check",
    executionStatus: "blocked",
    priority: "medium",
    assignedAgent: "human",
    linkedGithubRepo: "onyx-internal/marketing-site",
    githubIssueUrl: "https://github.com/onyx-internal/marketing-site/issues/23",
    githubPrUrl: null,
    deployUrl: null,
    branchName: null,
    blockedReason: "Need final list of routes the new CDN layer should probe.",
    needsDecision: true,
    nextStep: "Confirm canonical health path with infra.",
  },
  {
    projectSlug: "doc-platform",
    title: "Debug packet export issue",
    description: "Packet export drops attachments over 20MB in the worker path.",
    status: "inbox",
    executionMode: "github_issue",
    executionStatus: "queued",
    priority: "high",
    assignedAgent: "cursor",
    linkedGithubRepo: "onyx-internal/doc-platform",
    githubIssueUrl: "https://github.com/onyx-internal/doc-platform/issues/190",
    githubPrUrl: null,
    deployUrl: null,
    branchName: "investigate/packet-export-timeout",
    blockedReason: null,
    needsDecision: false,
    nextStep: "Reproduce with a seeded large case and inspect worker memory use.",
  },
  {
    projectSlug: "automations",
    title: "Add Docker build pipeline",
    description: "Standardize image builds so each agent can hand off a deployable container.",
    status: "ready",
    executionMode: "manual",
    executionStatus: "queued",
    priority: "medium",
    assignedAgent: "codex",
    linkedGithubRepo: "onyx-internal/automations",
    githubIssueUrl: null,
    githubPrUrl: null,
    deployUrl: null,
    branchName: "chore/docker-build-pipeline",
    blockedReason: null,
    needsDecision: false,
    nextStep: "Define a shared container tagging strategy.",
  },
  {
    projectSlug: "client-portal",
    title: "Decide DigitalOcean deployment mode",
    description: "Pick droplet vs App Platform before production hardening.",
    status: "blocked",
    executionMode: "deploy",
    executionStatus: "waiting_external",
    priority: "urgent",
    assignedAgent: "claude",
    linkedGithubRepo: "onyx-internal/client-portal",
    githubIssueUrl: null,
    githubPrUrl: null,
    deployUrl: null,
    branchName: null,
    blockedReason: "Needs an operator decision on cost vs managed operations.",
    needsDecision: true,
    nextStep: "Choose deployment mode and commit to rollout sequence.",
  },
  {
    projectSlug: "marketing-site",
    title: "Close homepage analytics audit",
    description: "Verify event mapping after the latest campaign launch.",
    status: "done",
    executionMode: "manual",
    executionStatus: "done",
    priority: "low",
    assignedAgent: "human",
    linkedGithubRepo: "onyx-internal/marketing-site",
    githubIssueUrl: null,
    githubPrUrl: null,
    deployUrl: null,
    branchName: null,
    blockedReason: null,
    needsDecision: false,
    nextStep: null,
  },
];

export const decisionSeeds = [
  {
    projectSlug: "automations",
    title: "GitHub sync approach",
    description: "Should the first GitHub sync use polling with stored cursors or webhook ingestion?",
    status: "open",
    resolution: null,
  },
  {
    projectSlug: "client-portal",
    title: "DigitalOcean deployment mode",
    description: "Decide whether client-portal should ship on App Platform or a droplet-managed Docker Compose host.",
    status: "open",
    resolution: null,
  },
  {
    projectSlug: "doc-platform",
    title: "Packet export retry cap",
    description: "Choose whether large packet exports should retry twice or move directly to manual review.",
    status: "resolved",
    resolution: "Retry twice, then hand off to manual review with an activity log event.",
  },
];

export const taskPromptSeeds = [
  {
    taskTitle: "Batch Clio handoff export",
    targetAgent: "codex",
    contextSummary: "doc-platform / github_pr / in_progress",
    prompt:
      "Task title: Batch Clio handoff export\nProject context: doc-platform\nGitHub context: issue #182, PR #188\nExpected output: summary, files changed, verification.",
  },
  {
    taskTitle: "Fix login redirect",
    targetAgent: "cursor",
    contextSummary: "client-portal / github_pr / review",
    prompt:
      "Task title: Fix login redirect\nProject context: client-portal staging\nGitHub context: issue #54, PR #61\nVerification requirements: regression-check reset and invite flows.",
  },
];

export const automationJobSeeds = [
  {
    action: "github_sync",
    status: "succeeded",
    projectSlug: "doc-platform",
    taskTitle: null,
    scopeLabel: "doc-platform",
    message: "GitHub sync completed and linked tasks were reconciled.",
  },
  {
    action: "runtime_refresh",
    status: "failed",
    projectSlug: "doc-platform",
    taskTitle: "Batch Clio handoff export",
    scopeLabel: "doc-platform runtime",
    message: "Runtime refresh detected degraded public traffic.",
    errorMessage: "Public URL returned 502 during the runtime refresh.",
  },
];
